services:
  api:
    container_name: trans-api
    build:
      context: requirements/api/
    develop:
      watch:
        - action: sync+restart
          path: requirements/api/src
          target: app/src
        - action: rebuild
          path: requirements/api/Dockerfile
    networks:
      - transcendence
    restart: always

  nginx:
    container_name: trans-nginx
    build:
      context: requirements/nginx/
    develop:
      watch:
        - action: sync+restart
          path: requirements/nginx/config/nginx.conf
          target: etc/nginx/nginx.conf
        - action: rebuild
          path: requirements/nginx/Dockerfile
    networks:
      - transcendence
    volumes:
      - frontend-dist:/var/www/html
    ports:
      - "4430:443"
    depends_on:
      - frontend
    secrets:
      - ssl_crt
      - ssl_key
    restart: always

  frontend:
    container_name: trans-frontend
    build:
      context: requirements/frontend
      target: ${TARGET}
    develop:
      watch:
        - action: sync
          path: requirements/frontend/src
          target: /app/src
        - action: sync
          path: requirements/frontend/public
          target: /app/dist
        - action: rebuild
          path: requirements/frontend/package.json
        - action: rebuild
          path: requirements/frontend/Dockerfile
    networks:
      - transcendence
    volumes:
      - frontend-dist:/app/dist

  pong:
    container_name: trans-pong
    build:
      context: requirements/pong/
    develop:
      watch:
        - action: sync+restart
          path: requirements/pong/src
          target: app/src
    networks:
      - transcendence
    restart: always

  tournament:
    container_name: trans-tournament
    build:
      context: requirements/tournament/
    develop:
      watch:
        - action: sync+restart
          path: requirements/tournament/src
          target: app/src
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    name: transcendence

volumes:
  frontend-dist:
    name: trans-frontend-dist

secrets:
  ssl_crt:
    file: ../secrets/ssl_certificate
  ssl_key:
    file: ../secrets/ssl_certificate_key
