services:
  api:
    image: trans-api
    container_name: trans-api
    build:
      context: requirements/api/
    networks:
      - transcendence
    expose:
      - "3000"
    restart: always

  nginx:
    image: trans-nginx
    container_name: trans-nginx
    build:
      context: requirements/nginx/
    networks:
      - transcendence
    # depends_on:
    #   - api
    ports:
      - "443:443"
    secrets:
      - ssl_crt
      - ssl_key
    restart: always

networks:
  transcendence:
    name: transcendence

secrets:
  ssl_crt:
    file: ../secrets/ssl_certificate
  ssl_key:
    file: ../secrets/ssl_certificate_key