version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data:
